# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Firebase CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Archive Build Project
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
  deploy:
    name: Deploy Project
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Build
      uses: actions/download-artifact@v3
      with:
          name: dist
          path: dist
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only hosting:chapter-front-avenue
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


